# Generated by Django 5.2 on 2026-05-25 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(editable=False, max_length=10, unique=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('listo', 'Listo para entrega'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=30)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.RESTRICT, related_name='pedidos', to='clientes.cliente')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.RESTRICT, related_name='pedidos', to='usuarios.empleado')),
            ],
            options={
                'db_table': 'pedido',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(max_length=30)),
                ('fecha_estado', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'estado_pedido',
                'ordering': ['-fecha_estado'],
            },
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_prenda', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('peso', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('cantidad', models.IntegerField(default=1)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='prendas', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'prenda',
            },
        ),
    ]
