# Generated by Django 5.2 on 2026-05-25 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_servicio', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'servicio',
                'ordering': ['nombre_servicio'],
            },
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('id_prenda', models.ForeignKey(db_column='id_prenda', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.prenda')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.RESTRICT, related_name='detalles', to='servicios.servicio')),
            ],
            options={
                'db_table': 'detalle_servicio',
            },
        ),
    ]
